### ISSUE TITLE
Problems with FG 3.7

### ISSUE THREAD

**Issue by 4wire** [lambersond/NotebookTheme#1]
If the image is stretched to full screen, the image controls are lost under the sidebar

**Comment by lambersond** [comment]
- The sizeup and sizedown buttons are now properly clickable and function as intended.
- The chat window will display overtop of an maximized image currently. Depending on the reception of this I can put it behind the image like everything else or it can stay on top.

Pull the latest release for the fix [v.1.0.5](https://github.com/lambersond/NotebookTheme/releases/tag/v1.0.5)
