### ISSUE TITLE
titles are all gone!

### ISSUE THREAD

**Issue by lambersond** [lambersond/NotebookTheme#6]
All the titles on windows have seemed to vanish.

**Comment by lambersond** [comment]
This seems to exist on FGU not FG classic.

**Comment by Gorg-Jorshwin** [comment]
Hi! I think that just got halfway fixed, the version I installed today is allowing me to see the full version of most of the titles. I'll try to add a picture for reference. Love your theme, by the way!
![image](https://user-images.githubusercontent.com/65043136/81445514-002ee400-9147-11ea-80a7-6e0f49bd574f.png)

**Comment by lambersond** [comment]
> Hi! I think that just got halfway fixed, the version I installed today is allowing me to see the full version of most of the titles. I'll try to add a picture for reference. Love your theme, by the way!
> ![image](https://user-images.githubusercontent.com/65043136/81445514-002ee400-9147-11ea-80a7-6e0f49bd574f.png)

I'll continue to watch this, but I believe that this will be resolved as FGU gets closer to being fully complete.

**Comment by lambersond** [comment]
This has resolved itself with an update to the FGU engine. No extension modifications required.

**Comment by lambersond** [comment]
@Gorg-Jorshwin let me know if you see any titles not being displayed and we'll reopen.

**Comment by Gorg-Jorshwin** [comment]
Thanks for your responses today! Want to commend you once again on an
excellent theme, I love it so much. I ran into an issue running the Portals
extension with Notebook in unity, I'll check again now to see if it still
clashes.
